### ISSUE TITLE
codegen the language server client from the spec?

### ISSUE THREAD

**Issue by devoncarew** [natebosch/dart_language_server#14]
I see that the language server client is codegened from here:

https://github.com/natebosch/dart_language_server/blob/master/lib/src/protocol/language_server/messages.yaml

Have you thought about generating it directly from the spec (https://github.com/Microsoft/language-server-protocol/blob/gh-pages/specification.md)? I think you could get a pretty parseable file by stripping out and concatenating all the code blocks from that markdown spec, and then generating a dart library from that.

**Comment by natebosch** [comment]
It would definitely be interesting to try. I'm not sure what the grammar is for their interface definitions - typescript maybe?

The two challenges I see are:

1. need to write a parser for this grammar.
2. need to automate how to handle the changes that don't translate to Dart, like type unions. When I manually translate to `messages.yaml` I can pick a type from the union (which might make us brittle?) or choose to make it `dynamic`.

The big benefits would be that I could pick up the documentation which I was too lazy to copy over, and that it would be easier to make it more general since I only ported over the messages I needed for the narrow features implemented here.

**Comment by devoncarew** [comment]
Yeah, some other benefits are that it can follow the spec as it changes, and that there are no inadvertent diffs from the spec. Having hand-written some of the lib can be useful in knowing where the hard parts to gen would be.

It does look like typescript, but you can probably just treat it as a generic IDL for your purposes. I wrote a quick and dirty parser for the IDL in the spec for the service protocol (https://github.com/dart-lang/vm_service_drivers/blob/master/dart/tool/dart/generate_dart.dart#L294); it may or may not help in parsing the definitions here.

**Comment by devoncarew** [comment]
https://github.com/dart-lang/vm_service_drivers/blob/master/dart/tool/common/parser.dart

**Comment by thosakwe** [comment]
Okay, so very closely related:

I was able to use ANTLR to put together a simple grammar to parse out interfaces and namespaces into Dart classes and constants:

https://github.com/thosakwe/ts_definition/blob/master/lib/src/grammar/TsInterface.g4
https://github.com/thosakwe/ts_definition/blob/master/lib/src/analysis/analysis.dart

And then this script does what @devoncarew suggested, and strips out the TypeScript sources from that spec and then generates these model classes:
https://github.com/thosakwe/lsp4dart/blob/master/tool/protocol.dart

The generated classes have serialization built-in, and are also strong-mode compatible, which is a plus.

I just noticed a few bugs here and there, but I can fix those by tomorrow. Hopefully this can help us find a solution here?

**Comment by natebosch** [comment]
Cool! That looks like a great start! How did you choose what to do with type unions?

Looks like a few places that could be typed are showing up as `dynamic` - for instance the type `DocumentUri` is equivalent to `String` so classes like `TextDocumentIdentifier` should be able to have a `String uri;`.

We'd also probably need things like hashCode and equality implemented - at least I rely on them here.

Also would be worth considering the final fields + builder pattern (like `built_value`). I currently use that pattern in my generated classes and I find the usage sites to be nice.

**Comment by thosakwe** [comment]
Fantastic, I'll probably end up copy your builder and hashCode implementations. Will credit you in the comments + README.

As for deciding what to do with unions, for now I have left them as `dynamic`, but analyzing the types a bit more to come up with accurate Dart representations should be relatively doable.

My next push will be slightly delayed, because I am rather behind on [this project](https://github.com/angel-dart/serialize).

---
Ultimately, it would be nice to abstract out a lot of the functionality into a generic `lsp` package.

My aim is to be able to use it here:
https://github.com/rapier-lang/rapier
https://github.com/rapier-lang/rapier/blob/master/lib/src/command/language_server.dart

Also, thank you for the cooperation, and fast responses. Really appreciate a lot.

**Comment by devoncarew** [comment]
Very cool!

https://github.com/thosakwe/lsp4dart/blob/master/lib/src/protocol/interfaces/interfaces.dart

/cc @DanTup, for the eventual dartification of Dart-Code.

**Comment by DanTup** [comment]
I've definitely got my eye on this project :-)

I don't know when Dart Code will be ported (I really want to get Web stuff done, also want to better support Fuchsia projects (eg. debugging) and now I'm distracted with some dabbling in the analysis server! 😄) but it seems like this would be a good way to avoid having so much of my own glue code!

**Comment by thosakwe** [comment]
Okay, so I've been able to finish that definition generator.

Some things:
* Implementing the builder pattern with classes the extend others would require extra static analysis, which I'm too lazy to add in. Also, the library isn't written very cleanly, so modifying things is a little messy. But doable.
* It actually seems pretty feasible to generate the server/client from the specification... I'll see if I can come up with some sort of a starter script for this.

**Comment by thosakwe** [comment]
It's not doing so well at extracting the proper response types, but this is what comes of it:

https://github.com/thosakwe/lsp4dart/blob/master/tool/api.dart
https://github.com/thosakwe/lsp4dart/blob/master/lib/src/protocol/server_base.dart
https://github.com/thosakwe/lsp4dart/blob/master/lib/src/protocol/client_base.dart

Stay tuned...

**Comment by natebosch** [comment]
I think the analysis server in the SDK has some level of scraping the spec and codegen.
