### ISSUE TITLE
Completions for named arguments include a trailing comma

### ISSUE THREAD

**Issue by natebosch** [natebosch/dart_language_server#16]
This makes it harder to autocomplete without 'snippet' handling.

**Comment by DanTup** [comment]
I don't know if it's related (title sounds like it, but I don't understand the comment about snippet handling) but I had an issue in Dart Code relating to named args with trailing commas:

https://github.com/Dart-Code/Dart-Code/issues/319

For Flutter code, the analysis server provides trailing commas to influence code formatting (feels wonky to me, but I understand why it's been done). In Dart Code I strip them off for the display, but keep them for the actual inserted text (to preserve the formatting behaviour preferred by Flutter).

**Comment by natebosch** [comment]
@DanTup - Do you also support the `selectionOffset` and `selectionLength` parameters to move the cursor before the comma when that completion is chosen?

What I meant by snippet handling was that I think I'd use the `$0` tabstop to move the cursor to before the comma (see [InsertTextFormat.Snippet](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion)). As is, most clients will leave the cursor after the comma which is not where the user wants to type next.

I think I'll likely strip them off for inserted text as well and have the user type it manually. If I'm get around to adding snippet completions I may leave in the comma for clients that support snippets.

**Comment by DanTup** [comment]
@natebosch Ah, I understand what you meant now. We do use `selectionOffset` etc. in Dart Code. 

https://github.com/Dart-Code/Dart-Code/blob/3cdca2e76ce30a09c9579ea409ade20d4b3b3da4/src/providers/dart_completion_item_provider.ts#L66-L71

```ts
} else if (suggestion.selectionOffset > 0) {
	const before = suggestion.completion.slice(0, suggestion.selectionOffset);
	const selection = suggestion.completion.slice(suggestion.selectionOffset, suggestion.selectionLength) || suggestion.parameterName;
	const after = suggestion.completion.slice(suggestion.selectionOffset + suggestion.selectionLength);

	completionText = escapeSnippetString(before) + `\${0:${escapeSnippetString(selection)}}` + escapeSnippetString(after);
}
```

The crazy logic here is because we need to escape everything for the snippet syntax and then also build snippets inside it. So we split the text into before/selection/after and escape them all, and then wrap the selection with `${0:xxx}`.

I haven't dug much into LSP much yet so I don't know how well this transfers (I'm interested in looking into it though; it might eliminate some of the mapping code in Dart Code - if you're at Dart Conf it'd be good to chat about it!).

I almost stripped the commas off for completion initially because it seemed wonky that the user ended up with the cursor in front of the comma after typing their value but then discovered that the analysis server doesn't add a trailing comma if there's already one after the cursor (https://github.com/dart-lang/sdk/issues/29909#issuecomment-309843674) so as long as the user figures that behaviour out (and is happy to just leave the comment after the cursor and type other args) then I don't think the experience is too bad.

**Comment by natebosch** [comment]
LSP does support a snippet syntax, so I could probably do something very similar to what you have to wrap the selection in the final tabstop. I'd still need a fallback for clients which don't support snippets - and since I haven't been motivated to implement snippet support the 'fallback' happens to be the only path :smile: 

> if you're at Dart Conf it'd be good to chat about it!

I'll be there!

**Comment by DanTup** [comment]
Fair enough! When I get time to start looking into LSP seriously for Dart Code I might try adding this then (if you don't beat me to it) :-)

> I'll be there!

Great, hope we can find some time to chat!
