### ISSUE TITLE
Completion gives bad suggestions in 'LanguageClient-neovim'.

### ISSUE THREAD

**Issue by PangPangPangPangPang** [natebosch/dart_language_server#26]
'dart_language_server' works fine with 'LanguageClient-neovim' except for auto complete.Hope for support this feature.
Some reason:
1. I need a common client rather then a client just for dart.
2. LanguageClient-neovim's perfermance looks better in my pc.
3. LanguageClient-neovim supports both vim and neovim.
Thx!

**Comment by natebosch** [comment]
What is the error you see? Do you have a request log?

**Comment by prabirshrestha** [comment]
could be the same issue where vim-lsp wasn't working. https://github.com/natebosch/dart_language_server/issues/27

**Comment by natebosch** [comment]
@PangPangPangPangPang - does `0.1.9+3` fix this for you?

Do you have any other details on the failure? Autocomplete is supported by this server, if there is a bug in the implementation I'll need more information to track it down.

**Comment by PangPangPangPangPang** [comment]
It give a wrong result first time I type in 'ad',but It give a right result when I delete 'ad' and type in again.
I can not get a wrong log using Analysis Server Diagnostics.
![image](https://user-images.githubusercontent.com/8207475/37578454-e4d5c894-2b73-11e8-8a84-87829e567092.png)

**Comment by natebosch** [comment]
https://github.com/autozimu/LanguageClient-neovim/issues/335 could be related and points out a very concrete issue, but it looks like a different failure to me.

@PangPangPangPangPang - to me that looks like we're not seeing the latest updates for the file before handling the completion. This could be a problem in either the client or the server.

There definitely was a potential source for this bug that I fixed in https://github.com/natebosch/dart_language_server/commit/3643bf6d8956c7215cbed52718f5f8263ab7c2f5
What version of the server are you using, if you're on earlier than `0.1.9+3` please upgrade as this is the likely source of the problem.

If you're already on the latest we need to make sure the client is flushing file changes before calling for the complete request. Can you record some communication logs and attach them so we can see the order requests are made in? You can check with the plugin you're using for how to set the `trace` parameter to `message` during initialization to have this log get written.

**Comment by natebosch** [comment]
This was most likely the async ordering issue that has been fixed. If you're still seeing problems please reopen with some communication logs and we can dig in.
