### ISSUE TITLE
LSP spec disallows explicit nulls, but many types are sending them

### ISSUE THREAD

**Issue by DanTup** [natebosch/dart_language_server#34]
I reported a bug to MS in VS that when `insertTextFormat` on `CompletionItem` was `null`, the completion hung with `Loading...`. They've pointed out that explicit nulls are not allowed unless specificied in the spec (the best description of this I can find is [here](https://github.com/Microsoft/language-server-protocol/issues/355#issuecomment-355999603)).

I don't know how easy it'd be to not send nulls, but seems like it's necessary to adhere to the spec.

**Comment by natebosch** [comment]
The alternative is to omit the field altogether? I think it's doable but we probably want to handle it in https://github.com/natebosch/message_builder

Do you think we need to specify this for each field or will it be safe to always drop null valued fields?

**Comment by DanTup** [comment]
> Do you think we need to specify this for each field or will it be safe to always drop null valued fields?

I'm not sure; I guess it depends whether the spec lists `| null` and `null` means something different to missing/undefined. It'll probably need a review of the spec (if you're generating from the spec it might be easy, otherwise it might be tedious :)).

I'll take a look through tomorrow and see whether there seem to be any significant `null`s.

**Comment by natebosch** [comment]
I'm not generating from the spec today. #14 is open to try that but every time I've tried thinking about what it would take it has seemed too daunting to try.

https://github.com/natebosch/dart_language_server/blob/master/lib/src/protocol/language_server/messages.yaml is my by-hand translation of the spec (or at least the subsets that are implemented by this server). I don't currently have a way to express per-field nullability but I don't think it would be hard to add if we need it.

**Comment by DanTup** [comment]
I had a quick look at `message_builder` but I'm not really sure how to do what we need. First I thought I'd just try skipping nulls when building the map in `toJson` (we could extend that to use metadata if we wanted finer control later).

Currently the code that generates toJson looks like this:

```dart
final toJson = new Method((b) => b
      ..returns = refer('Map')
      ..name = 'toJson'
      ..lambda = true
      ..body = literalMap(toJsonMap).code);
```

I guess we need to change `literalMap` to be a block of code that looks like this:

```dart
final x = new Map():
if (y2 != null)
  x[y1] = y2;
```

It's not clear how I can build an expression that creates the map and conditionally pushes the values based on the values (the conditions need to be inside the expressions). I had a look at what's being exported in `code_builder.dart` but nothing stands out.

If you can give me some pointers, I'm happy to take a look though!

**Comment by natebosch** [comment]
I pushed a branch which omits nulls at https://github.com/natebosch/dart_language_server/pull/37

This is relying an an uncommitted update in `message_builder` at https://github.com/natebosch/message_builder/pull/2

You're right on the general direction. The proof of concept I added is not as minimal as it should be - I'm always taking the json version of the expression and assigning to a variable, even when the field is a primitive and the expression isn't doing anything other than a reference. I think fixing this would require some refactoring, maybe changing the [`toJson`](https://github.com/natebosch/message_builder/blob/898a8a0b1a4b6577f27611bde45136823d6b04d3/lib/src/fields.dart#L108) implementations so that they can take another argument which is the expression they should assign to, and then handling the null check within each field. Unfortunately `code_builder` does not have a nice way to do conditional blocks today.

Another route we could consider is removing nulls before returning the result around here: https://github.com/natebosch/dart_language_server/blob/6fc8c84443862fb345edc60cd78f55a553df7d5a/lib/src/protocol/language_server/server.dart#L56

**Comment by DanTup** [comment]
Sorry for the delay, trying to get back to this this week. I'll try these branches out in VS and see if I get further. I'm not sure I have a good opinion on the choice between putting it in message_builder versus language_server - it's probably not that common that things will crash on nulls, but it also doesn't seem like a bad thing to let people control emitting nulls (I think some other serialisation libraries I used have); so probably either are reasonable :-)

**Comment by DanTup** [comment]
Ugh, I thought I'd responded her, but maybe not. This seems to work; the completion issue I had is gone with these branches :-)

**Comment by DanTup** [comment]
@natebosch Any thoughts on how to proceed with this? As a potentially quicker fix for my original issue, if we explicitly set insertTextFormat on CompletionItems; that should get my completions working without this (of course, we may find other failures, but this is the only one I know of for now).

**Comment by natebosch** [comment]
> As a potentially quicker fix for my original issue, if we explicitly set insertTextFormat on CompletionItems; that should get my completions working without this

I think we should start with that, do you want to open a PR? I'm not totally comfortable with these branches as they exist today and I'll need to find some time to clean them up.

**Comment by DanTup** [comment]
Sure, will do next week :)
