### ISSUE TITLE
Cannot launch server

### ISSUE THREAD

**Issue by l7ssha** [natebosch/dart_language_server#46]
Hello, I've encounter problem with configuring and launching server.
Emac's lsp-mode can't connect to it, and when started with command line it gives no meaningful output.

My emacs configuration: https://gist.github.com/l7ssha/491f6761bf44246dde7df36a356bee2b
OS: Arch Linux,  4.16.13-2-ARCH, zsh 5.5.1

If I missed some info - point it.

**Comment by natebosch** [comment]
We're in a rough place with the dart 2 transition. I don't think I've got all the dart 2 runtime issues ironed out but the basics have been working for me.

What sdk version are you on? What version of`dart_language_server` are you on? Have you tried rerunning the `pub global activate` since you've updated your sdk?

Could you try running the server outside of your editor and check if anything is printed to stderr?

**Comment by l7ssha** [comment]
I'm using `Dart VM version: 2.0.0-dev.55.0`. So this is an issue - I'll try with with 1.x runtime.
`dart_language_server` is `0.1.12+1`.

EDIT: Solved. I didn't knew that I'm using Dart 2.x.x. Now everything works just good. Thanks for help.
Also I think there should be disclaimer to use Dart 1.x

Created PR: https://github.com/natebosch/dart_language_server/pull/47

**Comment by natebosch** [comment]
The server has been working well for me in Dart 2 Mode - just takes a new `pub global activate` every once in a while. You might give it another shot.
