### ISSUE TITLE
Problem when navigating through symbols in the SDK

### ISSUE THREAD

**Issue by antekone** [natebosch/dart_language_server#49]
I'm having some problems when navigating symbols, but this problem occurs only when I'm trying to navigate through flutter/sdk dart files. When trying to navigate my own project files, everything works correctly and without any problems.

Maybe it will be best if I'll write what I'm doing:

1. Run `$ flutter create testapp`
2. Run `$ cd testapp`
3. Run `$ vim lib/main.dart`
4. No problems in navigating symbols here. Everything is properly and fully recognized. I'm able to jump to `StatefulWidget` definition, `Key` definition, etc.
5. Jump to the definition of `StatefulWidget` class
6. Observe that when the editor is inside the `flutter/lib/src/widgets/framework.dart` file, some classes that were recognized in `lib/main.dart` are not recognized anymore, like `Key` class.
7. Jump to the beginning of the `framework.dart` file, observe that there are lots of imports that aren't resolved, but some other imports are resolved OK. One of those invalid imports is an import of `package:flutter/foundation.dart`.
8. Go back to `lib/main.dart` file, try to import `package:flutter/foundation.dart` in this file, and it will succeed without problems.

Is this an intended behavior?

I've checked the Flutter/Dart plugin in VSCode and this plugin works when browsing symbols in SDK files, doesn't matter which file is opened at the moment.

I'm using:

    vim-lsc plugin

    dart_language_server 0.1.12+1
    
    Flutter 0.5.1 • channel beta • https://github.com/flutter/flutter.git
    Framework • revision c7ea3ca377 (5 weeks ago) • 2018-05-29 21:07:33 +0200
    Engine • revision 1ed25ca7b7
    Tools • Dart 2.0.0-dev.58.0.flutter-f981f09760

**Comment by natebosch** [comment]
The Dart SDK is working for me, the flutter SDK does cause me the same problems.

When I look at the server diagnostics it's because we end up adding a second analysis context (based on our call to `setAnalysisRoots`) for the file you jumped to. The Dart-Code plugin in vscode manages to avoid this somehow.

I can't figure out if its because the [`workspaceFolders`](https://github.com/Dart-Code/Dart-Code/blob/606e4b84a5229692ef1913d312bfcabc0ec341b7/src/utils.ts#L33) are automatically excluding them or something else.

@DanTup - did you need to do anything special to exclude adding an extra analysis root for files in the Flutter SDK after jumping to a definition within them?

**Comment by DanTup** [comment]
@natebosch I'm not sure I totally understand the problem, but Dart Code doesn't add additional analysis roots that you F12 into; we only set them foor the open workspaces. If you F12 into something we will add it as a priority file (because it's opened) but analysis roots are only every updated by opening/adding/removing folders in the workspace.

I don't know whether not having them as analysis roots is affecting any functionality (certainly nobody has mentioned anything not working; so maybe adding as priority files is enough?). Adding files individually as analysis roots is [not currently supported](https://github.com/dart-lang/sdk/issues/32256).

That said; should having additional analysis roots cause things to behave differently? I wouldn't have expected so; so maybe it's a server bug?

**Comment by natebosch** [comment]
What happens if you navigate into another package which is a `path` dependency? Does vscode automatically give you a new open workspace for that?

I think the issue is that LSP doesn't have a notion of  workspaces, so the best I'm able to do is check whether any file in a `didOpen` is not covered under an existing analysis root and add a new one if it isn't... maybe though I should be only adding an analysis root on the first open file or something? I think I ultimately need to approximate vscode's workspaces using only what I can glean from `didOpen` calls.

The additional analysis root that gets created is one that I attempt to automatically discovered based on things like `pubspec.yaml` files. It's not finding a good root for the files in the flutter SDK, which means that the analyzer doesn't set up the context correctly for flutter when you jump into the SDK.

**Comment by DanTup** [comment]
> What happens if you navigate into another package which is a `path` dependency? Does vscode automatically give you a new open workspace for that?

Nope, the workspaces are only the folders the user specifically added to the workspace.

Here's a log from me following the first few steps above (opening the new file, F12ing into the StatelessWidget).

[analyzer.txt](https://github.com/natebosch/dart_language_server/files/2173482/analyzer.txt)

LMK if you want me to try any specific steps (or if you have VS Code you can capture a log like this using [`Dart: Capture  Logs`](https://dartcode.org/docs/logging/#capture-logs-command) or the [`dart.analyzerLogFile` setting](https://dartcode.org/docs/logging/#analyzer).

**Comment by DanTup** [comment]
> The additional analysis root that gets created is one that I attempt to automatically discovered based on things like `pubspec.yaml` files. It's not finding a good root for the files in the flutter SDK, which means that the analyzer doesn't set up the context correctly for flutter when you jump into the SDK.

So what are your analysis roots after all this? I still think this should work - if you have an analysis root for the users project (which is the folder with the pubspec) and then the same for the flutter package with the StatelessWidget, I would've expected everything to just work.

**Comment by natebosch** [comment]
The Dart analysis server with `--lsp` has a different approach to managing context - if it exhibits the same bug as present here we'll need to investigate separately.
