### ISSUE TITLE
Adapt to use flutter analyzer inside Flutter projects

### ISSUE THREAD

**Issue by whoislewys** [natebosch/dart_language_server#67]
![image](https://user-images.githubusercontent.com/25728778/60357317-2cef6800-9988-11e9-8bb4-7b46eac753fe.png)

The dart analysis server has issues with Flutter functions

Running `flutter analyze --watch` will show live code suggestions. It would be nice to use the suggestions from flutter analyze inside flutter projects

There are (official suggestions in the flutter repo)[https://github.com/flutter/flutter/wiki/Using-the-Dart-analyzer] that might provide a direction

**Comment by natebosch** [comment]
My understanding is that `flutter analyze --watch` should not behave significantly differently from the default Dart SDK analysis server.

I'm surprised to see an `undefined_function` in your example, given that the class is defined in the same file - maybe your SDK is too old to omit the `new` when instantiating?

In any case the new way to use the analysis server with LSP is to start it with the `--lsp` flag instead of use `dart_language_server`. I'll update this repos README with that info. 

If you're using `vim-lsc` the easiest way to configure it is with `vim-lsc-dart` - https://github.com/natebosch/vim-lsc-dart

Otherwise if you're using a different plugin you'll need to find the location for the `dart` executable, then use it to find the `snapshots` directory and the analysis server snapshot. Then invoke with `--lsp`. You can see the details around https://github.com/natebosch/vim-lsc-dart/blob/8edbb6f49a3014ac3cf4c28965bc6722618ee9b0/ftplugin/dart.vim#L6-L19
