### ISSUE TITLE
Document how to use a specific dart SDK path

### ISSUE THREAD

**Issue by filmil** [natebosch/dart_language_server#68]
It would be nice if the `README.md` explained how one can use a custom dart SDK path.  This is useful say for projects that require the use of their own one.

I tried to infer the options from looking at the source code, but I have repeatedly failed to get results.  It would help tremendously if the docs explain how it is supposed to work.  Thanks!

**Comment by natebosch** [comment]
Whichever SDK is used to launch the server is the one that will be used for the analysis server. That happens around here: https://github.com/devoncarew/analysis_server_lib/blob/a119567329d79baa08ff199037e0b787125cef9a/lib/analysis_server_lib.dart#L73

This package doesn't contain that code - it's in a dependency, which is why it may have been hard to track down.

Note that the analysis server now has a `--lsp` flag to run in LSP mode and you shouldn't need this wrapper with recent SDKs.

Depending on your LSP client you'll want to configure it to startup the analysis server from the SDK's `bin/snapshots/` directory. You can see an example of finding the right command base on the `dart` from `$PATH` here:

https://github.com/natebosch/vim-lsc-dart/blob/8edbb6f49a3014ac3cf4c28965bc6722618ee9b0/ftplugin/dart.vim#L6-L19

**Comment by filmil** [comment]
Thank you!
